const { Sequelize, DataTypes } = require('sequelize');
const sequelize = require('../dbConfig');

const Facility = sequelize.define('facilities', {
    fac_id: { //Identity generated by default. Therefore can specify fac_id if needed
        type: DataTypes.SMALLINT,
        primaryKey: true,
        autoIncrement: true,
        allowNull: false
    },
    type: {
        type: DataTypes.STRING,
        allowNull: false,
        notEmpty: true
    },
    available: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
        defaultValue: true
    },
    price_per_hour: {
        type: DataTypes.DECIMAL(7, 2),
        allowNull: false,

    }
}, {
    timestamps: false
});

module.exports = Facility;